<a href="https://colab.research.google.com/github/Daniel-UTEC/etl-data-pipeline-2503162022/blob/Temporal/estudiantes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Carga de datos
import pandas as pd

url = "https://raw.githubusercontent.com/Daniel-UTEC/etl-data-pipeline-2503162022/refs/heads/main/data/raw/A_estudiantes.csv"

df = pd.read_csv(url)

df.head()

  id_estudiante             nombre edad                      correo
0         E1000         Raúl Gómez   26   carlos.castro45@correo.sv
1         E1001         Ana Castro   18  adriana.santos43@gmail.com
2         E1002   Ricardo Vásquez    23  maria.castro23@empresa.com
3         E1003        Sofía Gómez   27      luis.gomez77@correo.sv
4         E1004     Adriana Santos   26   elena.morales56@gmail.com

In [2]:
#Exploración de datos
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188 entries, 0 to 187
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_estudiante  178 non-null    object
 1   nombre         188 non-null    object
 2   edad           188 non-null    object
 3   correo         188 non-null    object
dtypes: object(4)
memory usage: 6.0+ KB

id_estudiante    10
nombre            0
edad              0
correo            0
dtype: int64

In [13]:
#Limpieza de datos
estudiantes = df.copy()

estudiantes.columns = estudiantes.columns.str.strip().str.lower()

for col in estudiantes.select_dtypes(include='object').columns:
    estudiantes[col] = estudiantes[col].astype(str).str.strip()

estudiantes.columns = estudiantes.columns.str.strip()

estudiantes['nombre'] = estudiantes['nombre'].str.strip()

estudiantes['edad'] = estudiantes['edad'].str.strip()

estudiantes['correo'] = estudiantes['correo'].str.strip()

estudiantes['edad'] = estudiantes['edad'].astype(str).str.replace(r'[a-zA-Z\sñÑáéíóúÁÉÍÓÚ]+', '', regex=True)

estudiantes['edad'] = pd.to_numeric(estudiantes['edad'])

estudiantes['nombre'] = estudiantes['nombre'].str.title()

estudiantes = estudiantes.drop_duplicates()

estudiantes.head()

  id_estudiante           nombre  edad                      correo
0         E1000       Raúl Gómez    26   carlos.castro45@correo.sv
1         E1001       Ana Castro    18  adriana.santos43@gmail.com
2         E1002  Ricardo Vásquez    23  maria.castro23@empresa.com
3         E1003      Sofía Gómez    27      luis.gomez77@correo.sv
4         E1004   Adriana Santos    26   elena.morales56@gmail.com

In [15]:
#Separar datos válidos y datos rechazados
validos = estudiantes[
    estudiantes['id_estudiante'].notna() &
    (estudiantes['id_estudiante'].astype(str).str.lower() != 'nan') &
    estudiantes['nombre'].notna() &
    estudiantes['edad'].notna() &
    estudiantes['correo'].notna()
].copy()

rechazados = estudiantes[
    estudiantes['id_estudiante'].isna() |
    (estudiantes['id_estudiante'].astype(str).str.lower() == 'nan') |
    estudiantes['nombre'].isna() |
    estudiantes['edad'].isna() |
    estudiantes['correo'].isna()
].copy()

In [16]:
# Colocar motivo de rechazo incluyendo el texto "nan"
def motivo(row):
    motivos = []


    def es_nulo_o_nan_text(valor):
        if pd.isna(valor):
            return True
        if str(valor).strip().lower() == "nan":
            return True
        return False

    if es_nulo_o_nan_text(row['id_estudiante']):
        motivos.append("id_estudiante_vacio")

    if es_nulo_o_nan_text(row['nombre']):
        motivos.append("nombre_vacio")

    if es_nulo_o_nan_text(row['edad']):
        motivos.append("edad_vacio")

    if es_nulo_o_nan_text(row['correo']):
        motivos.append("correo_vacio")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

In [17]:
#Exportar archivos
validos.to_csv("estudiantes_curated.csv", index=False)

rechazados.to_csv("estudiantes_rejects.csv", index=False)

In [18]:
#Conectar con PostgreSql Cloud
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_seguros_xmjb_user:MOAOhCFp0RSnjSynN6hL6D6GkhyiuY6s@dpg-d6qu75khg0os73b4ghu0-a.oregon-postgres.render.com/etl_seguros_xmjb"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 51.6 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
   ?column?
0         1

In [19]:
#Carga de datos en PostgreSQL
validos.to_sql(
    'estudiantes_curated',
    engine,
    if_exists='replace',
    index=False
)

rechazados.to_sql(
    'estudiantes_rejects',
    engine,
    if_exists='replace',
    index=False
)

8

In [22]:
#validar la carga de datos
pd.read_sql(
"SELECT * FROM estudiantes_curated LIMIT 10",
engine
)

  id_estudiante            nombre  edad                        correo
0         E1000        Raúl Gómez    26     carlos.castro45@correo.sv
1         E1001        Ana Castro    18    adriana.santos43@gmail.com
2         E1002   Ricardo Vásquez    23    maria.castro23@empresa.com
3         E1003       Sofía Gómez    27        luis.gomez77@correo.sv
4         E1004    Adriana Santos    26     elena.morales56@gmail.com
5         E1005      Carlos Pérez    26      diego.perez25empresa.com
6         E1006  Valeria Martínez    25      luis.romero1@outlook.com
7         E1007     Ana Hernández    22     elena.romero9@empresa.com
8         E1008    Carmen Vásquez    21   daniela.morales85@gmail.com
9         E1009      Andrés Mejía    20  natalia.rivera65@empresa.com

In [23]:
#validar la carga de datos
pd.read_sql(
"SELECT * FROM estudiantes_rejects LIMIT 10",
engine
)

,id_estudiante,nombre,edad,correo,motivo_rechazo
0,nan,Ana Santos,27,adriana.romero42@correo.sv,id_estudiante_vacio
1,nan,Gabriela Martínez,17,ricardo.ramirez84@gmail.com,id_estudiante_vacio
2,nan,Carlos Vásquez,22,ricardo.castro43@empresa.com,id_estudiante_vacio
3,nan,Miguel Morales,17,jose.guerrero28@empresa.com,id_estudiante_vacio
4,nan,Diego Mendoza,19,daniela.gomez98@outlook.com,id_estudiante_vacio
5,nan,Marta Romero,30,luis.morales96@correo.sv,id_estudiante_vacio
6,nan,Luis Pérez,24,valeria.ramirez10@correo.sv,id_estudiante_vacio
7,nan,Carlos Mejía,27,elena.romero19@outlook.com,id_estudiante_vacio